-- MySQL Script generated by MySQL Workbench
-- seg 09 set 2024 10:47:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema sistema_medico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_medico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS sistema_medico;

CREATE TYPE status_consulta AS ENUM ('agendada', 'realizada', 'cancelada');
CREATE TYPE status_pagamento AS ENUM ('pendente', 'realizado');
CREATE TYPE tipo_prescricao AS ENUM ('medicamento', 'exame', 'tratamento', 'atestado');
CREATE TYPE cargo_funcionario as ENUM ('recepcionista', 'medico');

-- -----------------------------------------------------
-- Table sistema_medico.funcionarios
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.funcionarios (
  cpf VARCHAR(11) NOT NULL,
  primeiro_nome VARCHAR(45) NULL,
  sobrenome VARCHAR(45) NULL,
  cargo cargo_funcionario NULL,
  telefone VARCHAR(11) NULL,
  PRIMARY KEY (cpf)
);


-- -----------------------------------------------------
-- Table sistema_medico.recepcionistas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.recepcionistas (
  cpf VARCHAR(11) NOT NULL,
  PRIMARY KEY (cpf),
  FOREIGN KEY (cpf)
  REFERENCES sistema_medico.funcionarios (cpf)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.medicos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.medicos (
  crm VARCHAR(12) NOT NULL,
  especialidade VARCHAR(45) NULL,
  cpf VARCHAR(11) NOT NULL,
  PRIMARY KEY (crm),
  FOREIGN KEY (cpf)
  REFERENCES sistema_medico.funcionarios (cpf)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.clinicas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.clinicas (
  cnpj VARCHAR(14) NOT NULL,
  nome VARCHAR(45) NULL,
  bairro VARCHAR(45) NULL,
  rua VARCHAR(45) NULL,
  numero INT NULL,
  cep VARCHAR (8) NULL,
  telefone VARCHAR(15) NULL,
  email VARCHAR(45) NULL,
  num_funcionarios INT NULL,
  PRIMARY KEY (cnpj)
);


-- -----------------------------------------------------
-- Table sistema_medico.locais
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.locais (
  id SERIAL,
  andar INT NULL,
  sala INT NULL,
  cnpj_clinica VARCHAR(14) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (cnpj_clinica)
  REFERENCES sistema_medico.clinicas (cnpj)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.

-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.consultas (
  id SERIAL,
  status status_consulta NOT NULL,
  motivo VARCHAR(45) NULL,
  data_horario TIMESTAMP NOT NULL,
  cpf_recepcionista VARCHAR(11) NOT NULL,
  crm_medico VARCHAR(12) NOT NULL,
  id_local INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (cpf_recepcionista)
  REFERENCES sistema_medico.recepcionistas (cpf)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  FOREIGN KEY (crm_medico)
  REFERENCES sistema_medico.medicos (crm)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  FOREIGN KEY (id_local)
  REFERENCES sistema_medico.locais (id)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.pagamentos
-- Table sistema_medico.pagamentos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.pagamentos (
  id SERIAL,
  data_de_pagamento TIMESTAMP NULL,
  forma_de_pagmaento VARCHAR(45) NULL,
  valor FLOAT NOT NULL,
  status status_pagamento NOT NULL,
  PRIMARY KEY (id)
);


-- -----------------------------------------------------
-- Table sistema_medico.pacientes
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.pacientes (
  cpf VARCHAR(11) NOT NULL,
  data_nascimento TIMESTAMP NULL,
  primeiro_nome VARCHAR(45) NULL,
  sobrenome VARCHAR(45) NULL,
  telefone VARCHAR(11) NULL,
  endereco VARCHAR(45) NULL,
  PRIMARY KEY (cpf)
);


-- -----------------------------------------------------
-- Table sistema_medico.planos_de_saude
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.planos_de_saude (
  cpf_paciente VARCHAR(11) NOT NULL,
  nome VARCHAR(45) NULL,
  cobertura VARCHAR(45) NULL,
  telefone VARCHAR(11) NULL,
  PRIMARY KEY (cpf_paciente),
  FOREIGN KEY (cpf_paciente)
  REFERENCES sistema_medico.pacientes (cpf)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.prescricoes
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.prescricoes (
  id_consulta INT NOT NULL,
  tipo tipo_prescricao NOT NULL,
  observacoes VARCHAR(255) NULL,
  PRIMARY KEY (id_consulta),
  FOREIGN KEY (id_consulta)
  REFERENCES sistema_medico.consultas (id) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.medicamentos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.medicamentos (
  id_prescricao INT NOT NULL,
  nome_generico VARCHAR(45) NULL,
  nome_comercial VARCHAR(45) NULL,
  dosagem VARCHAR(45) NULL,
  validade TIMESTAMP NULL,
  PRIMARY KEY (id_prescricao),
  FOREIGN KEY (id_prescricao)
  REFERENCES sistema_medico.prescricoes (id_consulta)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.exames
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.exames (
  id_prescricao INT NOT NULL,
  nome VARCHAR(45) NULL,
  preco DOUBLE PRECISION NULL,
  tipo VARCHAR(45) NULL,
  PRIMARY KEY (id_prescricao),
  FOREIGN KEY (id_prescricao)
  REFERENCES sistema_medico.prescricoes (id_consulta)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.tratamentos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.tratamentos (
  id_prescricao INT NOT NULL,
  data_emissao DATE NULL,
  data_fim DATE NULL,
  observacoes VARCHAR(255) NULL,
  PRIMARY KEY (id_prescricao),
  FOREIGN KEY (id_prescricao)
  REFERENCES sistema_medico.prescricoes (id_consulta)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.atestados
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.atestados (
  id_prescricao INT NOT NULL,
  data_inicio DATE NULL,
  data_fim DATE NULL,
  observacoes VARCHAR(255) NULL,
  PRIMARY KEY (id_prescricao),
  FOREIGN KEY (id_prescricao)
  REFERENCES sistema_medico.prescricoes (id_consulta)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table sistema_medico.fornecedores
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.fornecedores (
  cnpj VARCHAR(14) NOT NULL,
  nome VARCHAR(45) NULL,
  telefone VARCHAR(11) NULL,
  email VARCHAR(45) NULL,
  endereco VARCHAR(45) NULL,
  PRIMARY KEY (cnpj)
);


-- -----------------------------------------------------
-- Table sistema_medico.fornecedores_fornecem_medicamentos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.fornecedores_fornecem_medicamentos (
  cnpj_fornecedor VARCHAR(14) NOT NULL,
  id_medicamento INT NOT NULL,
  PRIMARY KEY (cnpj_fornecedor, id_medicamento),
  FOREIGN KEY (cnpj_fornecedor)
  REFERENCES sistema_medico.fornecedores (cnpj)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  FOREIGN KEY (id_medicamento)
  REFERENCES sistema_medico.medicamentos (id_prescricao)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table sistema_medico.clinicas_tem_funcionarios
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.clinicas_tem_funcionarios (
  id SERIAL,
  clinica_cnpj VARCHAR(14) NOT NULL,
  funcionario_cpf VARCHAR(11) NOT NULL,
  data_inicio DATE NULL,
  data_fim DATE NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (clinica_cnpj)
    REFERENCES sistema_medico.clinicas (cnpj)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (funcionario_cpf)
    REFERENCES sistema_medico.funcionarios (cpf)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table sistema_medico.transacoes_consultas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sistema_medico.transacoes_consultas (
  id SERIAL,
  id_pagamento INT NOT NULL,
  id_consulta INT NOT NULL,
  cpf_paciente VARCHAR(11) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_pagamento)
    REFERENCES sistema_medico.pagamentos (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (id_consulta)
    REFERENCES sistema_medico.consultas (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (cpf_paciente)
    REFERENCES sistema_medico.pacientes (cpf)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

